services:

* type: web
  name: ai-agent
  runtime: node
  plan: free

  buildCommand: npm install
  startCommand: npm start

  envVars:

  * key: GROQ_API_KEY
    sync: false

  * key: SUPABASE_URL
    sync: false

  * key: SUPABASE_SERVICE_ROLE_KEY
    sync: false

  * key: NODE_ENV
    value: production
